# In this notebook we go through the basics of  the tensorflow

In [ ]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [ ]:
vector = tf.constant([1,2])

In [ ]:
vector.ndim

1

In [ ]:
import numpy as np

random_array = np.random.random([4,6])

matrix = tf.constant(random_array)

In [ ]:
matrix.ndim

2

In [ ]:
unchangable = tf.constant(np.random.random([4,6,6,9]))

In [ ]:
unchanagable.ndim

NameError: name 'unchanagable' is not defined

In [ ]:
# the above are tf.constant so these cant be changed but there is another type which can be in changable form

In [ ]:
changable = tf.Variable(np.random.random([4,6]))

In [ ]:
changable[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(4, 6) dtype=float64, numpy=
array([[5.00000000e+00, 5.00000000e+00, 5.00000000e+00, 5.00000000e+00,
        5.00000000e+00, 5.00000000e+00],
       [5.61405906e-01, 4.31527422e-01, 8.82486837e-01, 8.08142110e-01,
        3.77849262e-01, 3.62697295e-01],
       [4.73640163e-01, 9.08493124e-01, 8.92635174e-01, 4.76921353e-01,
        6.68445968e-01, 2.18804468e-01],
       [1.67218452e-03, 6.45935582e-01, 6.24636035e-01, 8.05734250e-01,
        7.48647676e-01, 9.37416204e-01]])>

In [ ]:
unchangable[3].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Creating random tensors

In [ ]:
random = tf.random.Generator.from_seed(42)
a = random.uniform(shape = (6,7))

In [ ]:
b = random.normal(shape = (6,7))

In [ ]:
a==b

<tf.Tensor: shape=(6, 7), dtype=bool, numpy=
array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])>

In [ ]:
# shuffle the order of the elements in a tensor
not_shuffled = tf.constant(np.random.random([4,6]))

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.set_seed(42) # global seed
shuffled = tf.random.shuffle(not_shuffled,seed = 42) # operational seed

In [ ]:
shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(4, 6), dtype=float64, numpy=
array([[0.62395078, 0.03905412, 0.54223095, 0.26178174, 0.97873879,
        0.81617943],
       [0.13921114, 0.6826974 , 0.10391263, 0.05108492, 0.02044607,
        0.75128564],
       [0.50992421, 0.03056108, 0.96645731, 0.42588268, 0.59823324,
        0.35939805],
       [0.45450054, 0.08151765, 0.69360648, 0.69699442, 0.28625873,
        0.06211331]])>

In [ ]:
shuffled # the rows are shuffleed only

<tf.Tensor: shape=(4, 6), dtype=float64, numpy=
array([[0.13921114, 0.6826974 , 0.10391263, 0.05108492, 0.02044607,
        0.75128564],
       [0.50992421, 0.03056108, 0.96645731, 0.42588268, 0.59823324,
        0.35939805],
       [0.62395078, 0.03905412, 0.54223095, 0.26178174, 0.97873879,
        0.81617943],
       [0.45450054, 0.08151765, 0.69360648, 0.69699442, 0.28625873,
        0.06211331]])>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# getting information from the tensor

In [ ]:
rank_4_tensor = tf.zeros(shape = [1,2,3,4,5,6])

In [ ]:
a = tf.constant(rank_4_tensor,shape = [6,5,12,2])

In [ ]:
b = tf.constant(rank_4_tensor)

In [ ]:
rank_4_tensor.dtpe

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'dtpe'

In [ ]:
rank_4_tensor.ndim

6

In [ ]:
rank_4_tensor.shape

TensorShape([1, 2, 3, 4, 5, 6])

In [ ]:
rank_4_tensor.shape[0]

1

In [ ]:
rank_4_tensor.shape[-1] # elements along last axis

6

In [ ]:
tf.size(rank_4_tensor).numpy()

720

# Indexing

In [ ]:
# get first 2 element of each dimension
rank_4_tensor[:2,:2,:2,:2,:2,:2]

<tf.Tensor: shape=(1, 2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]],



        [[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]]], dtype=float32)>

In [ ]:
# get 1st element each dimension from each index except final one
rank_4_tensor[:1,:1,:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 1, 1, 6), dtype=float32, numpy=array([[[[[[0., 0., 0., 0., 0., 0.]]]]]], dtype=float32)>

In [ ]:
rank_5_tensor = rank_4_tensor[...,tf.newaxis]

In [ ]:
rank_5_tensor.ndim

7

# manipulating tensors

In [ ]:
tensor = tf.constant([[10,7],[9,8]])

In [ ]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [19, 18]], dtype=int32)>

In [ ]:
tensor # the original one isnt changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 9,  8]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 90,  80]], dtype=int32)>

In [ ]:
tensor*19

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[190, 133],
       [171, 152]], dtype=int32)>

In [ ]:
x = np.random.random([9,10])

In [ ]:
y = np.random.random([10,9])

In [ ]:
tensor = tf.matmul(x.T,y.T)

In [ ]:
tensor

<tf.Tensor: shape=(10, 10), dtype=float64, numpy=
array([[2.52635545, 3.37728851, 2.96744617, 3.17984514, 2.42973299,
        1.59646554, 2.48949213, 2.40404685, 2.53111191, 3.03605013],
       [2.97070846, 4.03803967, 3.50755632, 3.27942019, 3.13968081,
        2.5475001 , 2.68054449, 3.02915313, 3.17046483, 3.58463187],
       [2.20682975, 2.87052404, 2.64378994, 2.41233656, 2.23734966,
        1.99340819, 2.08762827, 2.51670132, 2.50298065, 2.57403847],
       [2.13047392, 2.93297273, 2.95139016, 2.35478135, 2.13299588,
        1.6517698 , 1.81328289, 1.92424796, 2.59038314, 2.57528084],
       [2.02690623, 2.39580354, 2.0221193 , 2.19067211, 1.91826263,
        1.30578579, 1.72301683, 1.87587583, 1.93518722, 2.09261172],
       [1.64276506, 2.65432891, 2.14515658, 2.36583342, 2.07436015,
        1.35851625, 1.82038381, 1.6690009 , 1.69178274, 2.07370713],
       [1.37778796, 2.17957172, 1.85406579, 1.61070676, 1.47150659,
        1.13455895, 1.07942832, 1.42658205, 1.36975262, 1.50

In [ ]:
x.T @ tf.reshape(y, shape = (9,10)) # this also multiplies haha

<tf.Tensor: shape=(10, 10), dtype=float64, numpy=
array([[2.15738878, 2.29572803, 2.81978533, 2.93777043, 3.08634611,
        2.80224476, 1.86922814, 2.6790365 , 2.5371037 , 2.59330719],
       [3.12780447, 2.70927271, 3.71038257, 3.58109626, 3.68421234,
        3.24679121, 2.70526697, 3.40160576, 3.06668034, 3.31903723],
       [2.63370903, 2.24659573, 2.31327666, 2.75816427, 2.33782273,
        2.31669816, 2.14500831, 2.55920235, 2.26440844, 2.25076737],
       [2.08523385, 1.85827996, 2.46361686, 2.57897425, 2.58880755,
        2.44596899, 1.64217811, 2.34300317, 2.38477817, 2.05968766],
       [1.95637895, 1.66841897, 2.5890256 , 1.96256021, 2.64665495,
        2.24863053, 1.56885045, 2.16727016, 1.7085485 , 1.89426444],
       [1.86966255, 1.69982806, 2.56071394, 1.87252127, 2.49877491,
        2.22240768, 1.77645021, 2.44491063, 2.03338451, 2.15439249],
       [1.56079875, 1.22878632, 1.50960968, 1.5566545 , 1.93204922,
        1.93146064, 0.93538472, 1.71971889, 1.71124766, 1.29

In [ ]:
tf.tensordot(x,y,axes = 1)

<tf.Tensor: shape=(9, 9), dtype=float64, numpy=
array([[3.11543482, 3.68502223, 3.47529282, 3.43250032, 3.0301497 ,
        2.57710841, 2.60336949, 2.91045042, 3.56010495],
       [2.60296209, 3.11243927, 3.36510743, 2.92581237, 2.45241651,
        1.97423593, 1.77661299, 2.49831064, 2.75407264],
       [2.26962349, 2.64099535, 2.70499793, 2.7411238 , 1.7514102 ,
        2.68604207, 2.31137331, 2.33514624, 2.16317596],
       [2.99775847, 3.12055575, 3.65006453, 3.3555821 , 2.74499263,
        2.85696039, 2.48128427, 2.79950262, 2.8207738 ],
       [2.51198047, 2.96975865, 3.22260727, 2.7956237 , 2.43405208,
        2.2835341 , 2.00760343, 2.33758977, 2.25046322],
       [1.736176  , 1.93368132, 2.43733163, 2.39384636, 1.59052457,
        2.16449666, 1.87923488, 1.92456833, 1.86597071],
       [2.90312995, 3.17779538, 2.7679872 , 2.67133305, 2.94824491,
        2.18409085, 1.99589362, 2.49246925, 2.74129387],
       [2.38257926, 3.43422191, 3.06034703, 3.06420825, 3.24158168,
        1

# changing the data type of tensor

In [ ]:
tensor = tf.cast(tensor, dtype = tf.float16)

# Aggregating tensor

In [ ]:
d = tf.constant([-9,8])

In [ ]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 8], dtype=int32)>

In [ ]:
g = tf.constant(np.random.randint(0,100,size = (20,20)))

In [ ]:
tf.size(g)

<tf.Tensor: shape=(), dtype=int32, numpy=400>

In [ ]:
g

<tf.Tensor: shape=(20, 20), dtype=int64, numpy=
array([[66, 20, 45, 62, 70, 52, 87, 25, 68, 15,  0, 61, 96,  0, 55, 21,
        84, 12, 75, 85],
       [86, 36, 10,  1, 29, 70, 30, 89, 11, 90,  0, 84, 34, 82, 52, 28,
        68, 29, 47, 32],
       [99, 18, 67, 75, 57, 76, 19, 54, 58, 34, 93, 33,  0, 47, 69, 52,
        73, 29, 14, 70],
       [21, 27, 79, 64,  8,  8, 85, 76, 34, 61, 95, 22, 19, 91,  5, 86,
        22, 74, 36, 85],
       [ 9, 78, 93, 56, 57, 95, 37, 76,  2, 96, 94,  4, 81, 19,  6, 69,
         2, 53, 49, 15],
       [ 8, 48, 73,  1,  1, 90,  8, 58, 70, 53, 15, 92, 29, 60, 39, 85,
        93,  7, 84, 80],
       [37, 40, 30, 12, 79, 80,  0,  1, 67, 28, 69, 30, 61, 73, 59,  8,
        48, 37, 49, 27],
       [26, 46,  9, 71, 12, 36, 94, 81, 74, 93, 76, 87, 40, 34, 46, 32,
         9, 57, 93, 32],
       [18, 84, 46, 88, 90, 73, 77, 65, 75, 45,  4, 85, 87, 64, 66, 76,
        91, 10, 92, 30],
       [86, 29, 74, 38, 33, 92,  5, 17, 21, 84, 73, 41, 85, 87, 71, 98,
       

In [ ]:
# find the min
tf.reduce_min(g)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(g)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(g)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
tf.reduce_sum(g)

<tf.Tensor: shape=(), dtype=int64, numpy=20145>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(g)

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([1005,  810,  789,  987,  901,  751,  935,  863,  782,  845, 1008,
        699,  835,  619,  533,  951,  957,  631,  890,  807])>

In [ ]:
tf.math.reduce_std(tf.cast(g,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.1299>

In [ ]:
tf.math.reduce_variance(tf.cast(g,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=848.5511>

# Finding positional min and max

In [ ]:
tf.argmax(g) #returns the index of highest no in each axis

<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([ 2, 14,  4, 12, 13,  4,  7, 17, 13,  4, 18,  5,  0,  3, 18,  9, 14,
       14, 12, 12])>

In [ ]:
tf.reduce_max(g)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

# Squeezing the tensor

In [ ]:
g = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))

In [ ]:
g_squeezed = tf.squeeze(g)

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed.shape


TensorShape([50])

# One Hot Encoding

In [ ]:
some_list = [0,1,2,3]

In [ ]:
tf.one_hot(some_list,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth = 4,on_value = "yes",off_value="NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'NO', b'NO', b'NO'],
       [b'NO', b'yes', b'NO', b'NO'],
       [b'NO', b'NO', b'yes', b'NO'],
       [b'NO', b'NO', b'NO', b'yes']], dtype=object)>

In [ ]:
tf.square(g)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
           1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
           5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-01,
           1.7738823e-02, 3.0037400e-01, 3.3017528e-01, 8.0943036e-01,
           8.9561006e-05, 2.7168143e-01, 4.0264672e-01, 3.9731771e-02,
           5.3205711e-01, 2.9793534e-01, 1.1570342e-02, 4.5793110e-01,
           4.3596479e-01, 1.1353558e-01, 3.6170322e-01, 4.4363216e-02,
           7.2716069e-01, 1.9414751e-01, 8.9970458e-01, 5.6418572e-02,
           6.5900785e-01, 2.7703318e-01, 2.4434039e-01, 4.6711516e-02,
           7.1524179e-01, 7.6018190e-01, 9.5102049e-02, 4.7169948e-01,
           5.6472950e-02, 6.1109054e-01, 9.3535668e-01, 4.7199135e-03,
           6.3798469e-01, 4.3597910e-01, 3.4474665e-01, 2.7098738e-02,
           5.4479504e-01, 1.0274617e-01]]]]], dtype=float32)>

In [ ]:
tf.math.sqrt(g)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.81520677, 0.6640834 , 0.59403914, 0.6815296 , 0.18346775,
           0.8274493 , 0.8603008 , 0.9340474 , 0.4757377 , 0.47243714,
           0.55712485, 0.8499034 , 0.36494818, 0.74031335, 0.7580296 ,
           0.9485165 , 0.09728138, 0.7219631 , 0.796583  , 0.44646198,
           0.8540623 , 0.7388062 , 0.32797185, 0.82262146, 0.81257385,
           0.5804743 , 0.7755112 , 0.45893982, 0.9234377 , 0.66379344,
           0.9739238 , 0.48736632, 0.90099555, 0.72549254, 0.7030704 ,
           0.4648962 , 0.91963017, 0.93374735, 0.5553253 , 0.8287363 ,
           0.4874837 , 0.88415086, 0.98343194, 0.26210994, 0.89372224,
           0.8125805 , 0.766258  , 0.40573013, 0.85912883, 0.5661629 ]]]]],
      dtype=float32)>

In [ ]:
tf.math.log(g)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[-0.40862694, -0.818695  , -1.0416201 , -0.7668313 ,
           -3.3914328 , -0.37881485, -0.3009464 , -0.13645622,
           -1.4857774 , -1.4997011 , -1.1699319 , -0.32526514,
           -2.0159998 , -0.6013634 , -0.5540658 , -0.10571226,
           -4.6602955 , -0.6515625 , -0.45484787, -1.612802  ,
           -0.31550223, -0.60543936, -2.229655  , -0.39051828,
           -0.4150969 , -1.0878195 , -0.50846565, -1.5576724 ,
           -0.15930387, -0.8195685 , -0.05284442, -1.4374784 ,
           -0.20850994, -0.641809  , -0.70459646, -1.5318823 ,
           -0.16756731, -0.13709876, -1.1764023 , -0.37570658,
           -1.4369967 , -0.2462551 , -0.03341366, -2.6779823 ,
           -0.22472048, -0.41508046, -0.5324727 , -1.8041341 ,
           -0.30367282, -1.1377468 ]]]]], dtype=float32)>

In [ ]:
tf.math.exp(g)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[1.9436393, 1.5542712, 1.4231639, 1.5911906, 1.0342333,
           1.983122 , 2.0961816, 2.392753 , 1.2539848, 1.2500666,
           1.3639543, 2.0592375, 1.1424638, 1.7299005, 1.7764355,
           2.4588246, 1.0095086, 1.684099 , 1.8861628, 1.2205826,
           2.0738826, 1.7260482, 1.1135638, 1.9673866, 1.9353269,
           1.4006696, 1.8247038, 1.2344503, 2.3460596, 1.5536729,
           2.5819051, 1.2681079, 2.251942 , 1.6927246, 1.6393634,
           1.2412618, 2.3296537, 2.3914123, 1.3612266, 1.9873534,
           1.268253 , 2.1852336, 2.6304066, 1.0711166, 2.2227373,
           1.9353479, 1.7988567, 1.1789414, 2.0919619, 1.3778722]]]]],
      dtype=float32)>

In [ ]:
# converting tensor to numpy is
np.array(g)

array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)

In [ ]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
